{
 "title": "Network calls stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request execution time python.org: true histogram",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "gt" ], "type": "tag" },
      { "params": [ "le" ], "type": "tag" }
     ],
     "measurement": "aiohttp-request-exec-time",
     "select": [
      [
       { "params": [ "value_bucket" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "www.python.org" }
     ]
    }
   ]
  },
  {
   "title": "Request execution time mozilla.org: true histogram",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "gt" ], "type": "tag" },
      { "params": [ "le" ], "type": "tag" }
     ],
     "measurement": "aiohttp-request-exec-time",
     "select": [
      [
       { "params": [ "value_bucket" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "www.mozilla.org" }
     ]
    }
   ]
  },
  {
   "title": "Request time heatmap python.org",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "aiohttp-request-exec-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "www.python.org" }
     ]
    }
   ]
  },
  {
   "title": "Request time heatmap mozilla.org",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "aiohttp-request-exec-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "www.mozilla.org" }
     ]
    }
   ]
  },
  {
   "title": "requests exec time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests-request-exec-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "call-python-and-mozilla-using-requests-exec-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "aiohttp exec time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aiohttp-request-exec-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "call-python-and-mozilla-using-aiohttp-exec-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "aiohttp resolve host and create conn time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aiohttp-connection-create-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aiohttp-dns-resolvehost-time",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "dns cache miss, hit and reuseconn",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aiohttp-dns-cache-miss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aiohttp-connection-reuseconn",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "requests and aiohttp exceptions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "exception-class" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "aiohttp-request-exception",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "exception-class" ], "type": "tag" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "requests-request-exception",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}